# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-21 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICOModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ico_start_date', models.DateField(), ),
                ('ico_end_date', models.DateField()),
                ('min_cap_in_eth', models.CharField(max_length=10)),
                ('max_cap_in_eth', models.CharField(max_length=10)),
                ('tokens_per_eth', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('max_token_supply', models.CharField(max_length=10)),
                ('for_sale', models.CharField(max_length=10)),
                ('white_label_address', models.CharField(max_length=10)),
                ('admin_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
